modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"
issueTrackerURL = "https://github.com/Sarinsa/InstantDeath/issues"

[[mods]]
logoFile = "banner.png"
authors = "Sarinsa, Father Toast"
credits = "Yeah :)"
version = "${file.jarVersion}"
displayName = "Swift Death"
modId = "swiftdeath"
description = '''
A simple mod that allows you to configure damage types to insta-kill players or other living creatures.

Download: https://www.curseforge.com/members/sarinsa/projects

Source: https://github.com/Sarinsa/InstantDeath

Discussion: https://discord.gg/GFTzTdX/
'''

[[dependencies.swiftdeath]]
modId = "forge"
mandatory = true
versionRange = "[47.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.swiftdeath]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.swiftdeath]]
modId = "crust"
mandatory = true
versionRange = "[4.9.15,)"
ordering = "BEFORE"
side = "BOTH"

# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="" #optional
